### ISSUE TITLE
AutoStandardize 优化的排版格式会在划重点之后变成未优化的格式

### ISSUE THREAD

**Issue by SnakeHit** [mnaddon/ohmymn#51]
Mac用户：版本12.3
Marginnote版本：3.7.16最新版
摘录原文
<img width="913" alt="image" src="https://user-images.githubusercontent.com/45898625/159727490-4ef8b947-28fb-439c-99fa-5234baaaf250.png">
划重点前的脑图
<img width="338" alt="image" src="https://user-images.githubusercontent.com/45898625/159727590-9a629437-b452-42f9-90dd-74901d5a7fd3.png">
可以看到AutoStandardize和autolist优化的很好，但划重点后
<img width="325" alt="image" src="https://user-images.githubusercontent.com/45898625/159728045-27859dfc-8ba1-4ca0-a2b8-3b1b77c610a7.png">

**Comment by ourongxing** [comment]
![image](https://user-images.githubusercontent.com/48356807/159874901-17be2f2a-dc9a-4191-910b-270394fc8fc7.png)
