### ISSUE TITLE
AnotherAutoTitle 拖拽标题文字到摘录中后，评论未立即删除

### ISSUE THREAD

**Issue by SnakeHit** [mnaddon/ohmymn#57]
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/45898625/163682494-d790f457-5f5a-414a-889f-96ca3dd20dd8.png">
类似于这种情况，不像视频中立即删除。
**但在mac中使用 ⌘ + tab 切换到其他软件，再切换回来就删除了该评论**
或者就是下一次摘录后，这个额外的评论会消失
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/45898625/163682588-b79669d6-6067-457c-bee2-43e4675a9f80.png">
同样在 ipad 也是这种情况

**Comment by ourongxing** [comment]
是这样设计的，延时删除，这样你可以有机会修改
