### ISSUE TITLE
【AutoTag】非常实用的功能建议：批量选中特定正则表达式筛选的笔记并添加标签

### ISSUE THREAD

**Issue by clark874** [mnaddon/ohmymn#8]
作者好，感谢快速回复！刚刚看到你之前在另一个加标签的插件里回复，这里想提一个ohmymn能实现的很实用的加标签功能，即用正则表达式筛选出包含特定字符的笔记（比如标题中有“自然语言处理”），然后再利用官方加标签的方式加入标签。

这个功能的用处在于，很多人不喜欢摘录时操作太多，但事后整理时需要用标签，所以事后添加标签是非常常见的。但问题在于标签需要选中大量笔记，这个耗时耗力，反而是ohmymn里的正则表达式可以实现很容易的批量筛选操作，所以只要选中后用官方的加标签方式加标签就很方便了。

希望作者考虑实现，应该非常容易。

谢谢！

**Comment by ourongxing** [comment]
可以实现，记下了，你可在在这里补充一下具体的细节

**Comment by ourongxing** [comment]
不过筛选是可以，但是选中还是要自己选中，不然不符合 ohmymn 的使用逻辑，你可以选中全部，然后 ohmymn 可以在满足条件的卡片添加标签

**Comment by clark874** [comment]
谢谢作者。

我觉得可以起名AutoTag，包含三个功能栏，第一个是正则表达式批量选中标题中包含特定词的笔记，第二个是正则表达式批量选中摘录中包含特定词的笔记，第三个是正则表达式批量选中笔记和摘录中任意一个包含特定词的笔记。

如果还能进一步设计，可以把添加标签的操作包含在插件里。这实际上只是添加一条评论：#标签内容。换句话说就是实现为批量选中的笔记加入特定格式的评论。如果能够实现，我理解会比官方的添加标签操作更简洁。当然，如果技术上有难度，可以只实现批量选中功能就行。

更高级的功能，我觉得可以实现自动添加标签，即在摘录时如果摘录文本包含特定词，就自动为笔记加上特定标签。

**Comment by clark874** [comment]
> 不过筛选是可以，但是选中还是要自己选中，不然不符合 ohmymn 的使用逻辑，你可以选中全部，然后 ohmymn 可以在满足条件的卡片添加标签

这个可以，最麻烦的操作是筛选笔记的部分，全选后使用插件可以接受。

**Comment by ourongxing** [comment]
非常好的建议，在完成 autodef 后会来实现，不过我预计的是一个月一个新功能，可能要等到 11 月了。后期还有选中当前卡片的兄弟卡片，选中所有卡片的功能，使得这些功能更为方便使用。
